### ISSUE TITLE
404 when accessing public url

### ISSUE THREAD

**Issue by RagingRoosevelt** [AndrewJesse/can_project_docker#2]
I get a 404 - deployment not found error when visiting https://can-project-docker.vercel.app/

![image](https://github.com/user-attachments/assets/112d916c-bb92-4a9a-a2cc-44c2a025bc3a)

**Comment by AndrewJesse** [comment]
Issue has been repaired and https://can-project-docker.vercel.app/ is active now. Triggered a fresh deployment to ensure that there are no cached issues. git commit --allow-empty -m "Trigger redeploy"

**Comment by AndrewJesse** [comment]
I fixed the 404 issues but unfortunately found out that SQLite isn't supported by Vercel so I couldn't get the table data to show up on the public page. I might have to remove the Vercel feature altogether to keep the repo user-friendly since there aren't any free or easily set up options available. Thanks!

**Comment by RagingRoosevelt** [comment]
Yeah, free hosting seems increasingly rare =(
